CREATE TABLE "airr_rearrangement" (
  "airr_rearrangement_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cell_id" varchar,
  "clone_id" varchar,
  "sequence_id" varchar,
  "sequence" varchar,
  "sequence_aa" varchar,
  "productive" varchar,
  "rev_comp" varchar,
  "v_call" varchar,
  "v_cigar" varchar,
  "d_call" varchar,
  "d_cigar" varchar,
  "j_call" varchar,
  "j_cigar" varchar,
  "c_call" varchar,
  "c_cigar" varchar,
  "sequence_alignment" varchar,
  "germline_alignment" varchar,
  "junction" varchar,
  "junction_aa" varchar,
  "junction_length" int,
  "junction_aa_length" int,
  "v_sequence_start" int,
  "v_sequence_end" int,
  "d_sequence_start" int,
  "d_sequence_end" int,
  "j_sequence_start" int,
  "j_sequence_end" int,
  "c_sequence_start" int,
  "c_sequence_end" int,
  "consensus_count" int,
  "duplicate_count" int,
  "is_cell" varchar(1)
);

CREATE TABLE "clonotypes" (
  "clonotype_id" varchar PRIMARY KEY,
  "frequency" int,
  "proportion" float,
  "cdr3s_aa" varchar,
  "cdr3s_nt" varchar,
  "inkt_evidence" varchar,
  "mait_evidence" varchar
);

CREATE TABLE "consensus_annotations" (
  "clonotype_id" varchar,
  "consensus_id" varchar PRIMARY KEY,
  "length" int,
  "chain" varchar,
  "v_gene" varchar,
  "d_gene" varchar,
  "j_gene" varchar,
  "c_gene" varchar,
  "full_length" varchar(4),
  "productive" varchar(4),
  "fwr1" varchar,
  "fwr1_nt" varchar,
  "cdr1" varchar,
  "cdr1_nt" varchar,
  "fwr2" varchar,
  "fwr2_nt" varchar,
  "cdr2" varchar,
  "cdr2_nt" varchar,
  "fwr3" varchar,
  "fwr3_nt" varchar,
  "cdr3" varchar,
  "cdr3_nt" varchar,
  "fwr4" varchar,
  "fwr4_nt" varchar,
  "reads" int,
  "umis" int,
  "v_start" int,
  "v_end" int,
  "v_end_ref" int,
  "j_start" int,
  "j_start_ref" int,
  "j_end" int,
  "fwr1_start" int,
  "fwr1_end" int,
  "cdr1_start" int,
  "cdr1_end" int,
  "fwr2_start" int,
  "fwr2_end" int,
  "cdr2_start" int,
  "cdr2_end" int,
  "fwr3_start" int,
  "fwr3_end" int,
  "cdr3_start" int,
  "cdr3_end" int,
  "fwr4_start" int,
  "fwr4_end" int
);

CREATE TABLE "filtered_contig_annotations" (
  "filtered_contig_annotations_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "barcode" varchar,
  "is_cell" varchar(4),
  "contig_id" varchar,
  "high_confidence" varchar(4),
  "length" int,
  "chain" varchar,
  "v_gene" varchar,
  "d_gene" varchar,
  "j_gene" varchar,
  "c_gene" varchar,
  "full_length" varchar(4),
  "productive" varchar(4),
  "fwr1" varchar,
  "fwr1_nt" varchar,
  "cdr1" varchar,
  "cdr1_nt" varchar,
  "fwr2" varchar,
  "fwr2_nt" varchar,
  "cdr2" varchar,
  "cdr2_nt" varchar,
  "fwr3" varchar,
  "fwr3_nt" varchar,
  "cdr3" varchar,
  "cdr3_nt" varchar,
  "fwr4" varchar,
  "fwr4_nt" varchar,
  "reads" int,
  "umis" int,
  "raw_clonotype_id" varchar,
  "raw_consensus_id" varchar,
  "exact_subclonotype_id" int
);

CREATE TABLE "barcodes" (
  "barcode_id" varchar PRIMARY KEY
);

ALTER TABLE "consensus_annotations" ADD FOREIGN KEY ("clonotype_id") REFERENCES "clonotypes" ("clonotype_id");

ALTER TABLE "airr_rearrangement" ADD FOREIGN KEY ("clone_id") REFERENCES "clonotypes" ("clonotype_id");

ALTER TABLE "filtered_contig_annotations" ADD FOREIGN KEY ("raw_clonotype_id") REFERENCES "clonotypes" ("clonotype_id");

ALTER TABLE "airr_rearrangement" ADD FOREIGN KEY ("cell_id") REFERENCES "barcodes" ("barcode_id");

ALTER TABLE "filtered_contig_annotations" ADD FOREIGN KEY ("barcode") REFERENCES "barcodes" ("barcode_id");
